### ISSUE TITLE
Group 의 addMesh, addGroup

### ISSUE THREAD

**Issue by shallaa** [projectBS/MOGL#1]
http://ligo.kr/r65

Group 문서 작성중에...
구지 addMesh와 addGroup같은 분류가 필요한지 고민중.
addMesh로 Group도 같이 등록을 하거나 addChild, getChild, removeChild 처럼 child 하나로 Mesh와 Group을 같이 등록, 제거도 가능할 듯.
고민은.. child의 child의 child의 child, ... 이런 경우의 처리를 위해 addGroup으로 분류는 꼭 필요해 보이기도 해서...

**Comment by hikaMaeng** [comment]
이미 Scene을 보면 addMesh로 통합.
Group은 상속구조가 Mesh로부터 파생.

Group extends Mesh
Camera extends Mesh

**Comment by shallaa** [comment]
옙. :)
