### ISSUE TITLE
JSLint 적용

### ISSUE THREAD

**Issue by shallaa** [projectBS/MoGL#137]
* **BlendMode**
* **Camera**
* **Filter**
* **Geometry**
* Group
* Light
* **Material**
* Material_
* Mesh
* MoGL
* Primitive
* Scene
* **Shading**
* **Texture**
* Vertex
* VertexShaderFunctions
* **World**

**Comment by redcamel** [comment]
이건 어떻게 적용해봐야하는건가요

**Comment by shallaa** [comment]
웹스톰에도 옵션이 있고 돌려보는 수 밖에. :)
돌려보고 => 수정하고 노가다.

**Comment by shallaa** [comment]
완료!!!
