### ISSUE TITLE
Material - Scene이 상위에 없을 때

### ISSUE THREAD

**Issue by sjshin-simpson** [projectBS/MoGL#184]
![2015-05-23 11 02 46](https://cloud.githubusercontent.com/assets/11942622/7784419/fd74e818-019f-11e5-8377-ca0a9d41110c.png)

이상황일때 error가 필요하지 않을까요???

**Comment by shallaa** [comment]
생성되지 않은 Texture를 추가하는 케이스인거에요?

**Comment by sjshin-simpson** [comment]
넵 생성되지 않고 씬에도 추가되지 않은 케이스입니다.
기존에 error는 씬에는 추가되고 텍스쳐가 생성되지 않은 케이스에만 error를 뿜어서요..

**Comment by redcamel** [comment]
아니요 이건 에러가 안나는게 맞습니다..
일단 키로 추가하고...
키를 기반으로 씬에 등록될때 판단하는 시나리오라..
