### ISSUE TITLE
Material - setEdge 구현

### ISSUE THREAD

**Issue by sjshin-simpson** [projectBS/MoGL#186]
setEdge 라는 메서드가 문서상에 나와있는데 소스상에는 구현이 안되어있어서요.

이슈사항들에서도 따로 안보여서 이슈에 올려놓습니다.

일단 마스터님에게..확인하시고 라벨바꿔주세요.

**Comment by redcamel** [comment]
이게 프레임버퍼관련이라 0.3으로..보냄
