### ISSUE TITLE
Material - addTexture index param Bug

### ISSUE THREAD

**Issue by sjshin-simpson** [projectBS/MoGL#197]
![2015-05-24 6 23 49](https://cloud.githubusercontent.com/assets/11942622/7787352/8c59a530-0242-11e5-8281-c4a30cda411a.png)

index parameter 값에 대한 기대 값이 안나와서 등록합니다.

**Comment by redcamel** [comment]
음 이게 리스트 갯수보다 큰수를 지정했을때 어떻게 처리하냐의 문제군요..
