### ISSUE TITLE
Mesh 메소드 setGeometry, setMaterial 사용시 문제

### ISSUE THREAD

**Issue by pparkssi** [projectBS/MoGL#204]
Mesh 생성자, setGeometry, setMaterial 에 scene에 등록 되지 않은 Geometry, Material id 값을 주고 

scene에 addChild 하거나 

scene에 정상 등록된 Mesh에 scene에 등록 되지 않은 Geometry, Material id를 

setGeometry, setMaterial 파라미터로 넣어주면 에러 발생합니다.

**Comment by redcamel** [comment]
음 이건 정상아닌가 싶은디

**Comment by pparkssi** [comment]
문서에 정의 된 예외가 발생해야 할것 같은데 참조에러가 발생해서 등록했어요

**Comment by redcamel** [comment]
https://github.com/projectBS/MoGL/blob/master/doc/Mesh.md#setgeometry-geometry-
여기보시면..
addChild 이전이라면 id계열의 객체가 Scene에 존재하는지 검사하지 않고, 이후라면 즉시 검사함.
이라고 되어있습니다....

즉 씬에 정상등록된 Mesh라면...
setGeometry나 setMAterial 할떄 즉시 있는놈있지 없는 놈인지 판단해서 에러를 발생

**Comment by redcamel** [comment]
음 고민되네요..
같은 에러메시지로는 판별이 애매한데...나눠버릴까요..
