### ISSUE TITLE
MoGL에서 사용 중인 UV 좌표계의 원점 관련

### ISSUE THREAD

**Issue by hanmomhanda** [projectBS/MoGL#208]
인터넷 찾아보면 UV 좌표계의 원점을 좌상단으로 하는 자료도 있고, 좌하단으로 하는 자료도 있네요.
이런 걸로 볼 때 UV 좌표계의 원점은 어디다!! 라고 WebGL 스펙에 정해져 있지는 않은 걸로 추정 됩니다.
(게을러서 스펙까지는 몬 뒤져보겠고.. ㅋㅋ)

암튼 그런데 **MoGL에서는 UV 좌표계의 원점이 다소 특이하게 우상단**으로 되어 있는 것 같습니다.

https://github.com/projectBS/MoGL/blob/dev/src/Primitive.js 에서 34라인에 있는 정점 정보를 보면,
주석 처리가 되어 있기는 하지만 **XYZ 좌표계의 우상단인 1, 1, 0 을 UV 좌표계의  0, 0 으로 하고 있습니다.**
실제로도 테스트 해보면 우상단을 UV 좌표계의 원점으로 가정하고 u, v 값을 계산해야 이미지의 좌우가 바뀌지 않게 나오더군요.

**직관적으로는 원점은 우측이 아니라 좌측에, 위/아래까지 정하자면, 좌상단에 있는 것이 좋지 않을 까 합니다.**

**Comment by redcamel** [comment]
규정점은 없습니다..
사실...저희 프리미티브도...컬링으 대비해서...드로잉순서도....통일해야하는 문제부터 존재합니다 ㅎㅎ

**Comment by redcamel** [comment]
좌상단으로 픽스하는 걸로
