### ISSUE TITLE
Primitive Scale 1로 수정 및 중앙점 0.0을 기본으로함

### ISSUE THREAD

**Issue by redcamel** [projectBS/MoGL#229]

**Comment by hanmomhanda** [comment]
Primitive.polygon()은 #247 에서 본 내용 적용함. Primitive의 메서드 중 구현된 것들은 모두 파라미터 radius를 사용하지 않으며, 앞으로도 구현될 메서드도 파라미터 radius를 사용하지 않는 것으로 공유했으므로 close 처리
