### ISSUE TITLE
신규 Matrix 점검

### ISSUE THREAD

**Issue by redcamel** [projectBS/MoGL#257]
https://github.com/projectBS/MoGL/blob/master/doc/Matrix.md

**Comment by hanmomhanda** [comment]
mat1.multiply(mat2) 가 mat1 * mat2 를 의미하는지, mat2 * mat1 를 의미하는지 모르겠지만, 현재 구현은 mat2 * mat1 로 되어 있음

**Comment by hanmomhanda** [comment]
X, Y, Z축 기준 회전 계산식이 시계 방향 회전을 기준으로 작성되어 있음.

**Comment by hanmomhanda** [comment]
이동 변환(translate)을 위한 계산식이 잘못 구성되어 있는 것으로 추정.
셰이더에서는 mat4()를 쓰기 때문에
```
mat4(
1 0 0 0
0 1 0 0
0 0 1 0
x y z 1
)
```
로 작성하지만, 원래 이동 변환 계산을 위한 행렬은
```
1 0 0 x
0 1 0 y
0 0 1 z
0 0 0 1
```
이며, 셰이더의 mat4()를 사용하지 않는다면 아래 쪽의 행렬이 올바른 이동 변환 행렬임

**Comment by redcamel** [comment]
miltiplay는 교정했음
