### ISSUE TITLE
World 변경에 따른 test html, showcase 점검

### ISSUE THREAD

**Issue by pparkssi** [projectBS/MoGL#286]
World 변경에 따른 testcase, showcase 점검

**Comment by shallaa** [comment]
전체 다 점검해야 하는거죠? 
할당 나누어서 해치워버릴까요?

**Comment by fabulousu** [comment]
Camera.html
renderArea : FAIL

맥북레티나 사파리, 크롬

**Comment by hanmomhanda** [comment]
Primitive는 제가 할께요~

**Comment by shallaa** [comment]
이슈 클로즈합니다.
관련 이슈가 발생시 새로 관련 이슈 등록해주세요.
