### ISSUE TITLE
[Showcase] textureOption

### ISSUE THREAD

**Issue by shallaa** [projectBS/MoGL#344]
IndexSizeError

**Comment by redcamel** [comment]
인덱스 사이즈에러가 정확히 머죠

**Comment by redcamel** [comment]
정상동작하는듯한데

**Comment by shallaa** [comment]
![indexsizeerror](https://cloud.githubusercontent.com/assets/1772173/8288207/a380b4b4-194f-11e5-868d-747761e33934.PNG)

**Comment by shallaa** [comment]
확인할 수 있는 상태로 다시 푸시하겠음.

**Comment by shallaa** [comment]
http://projectbs.github.io/MoGL/showcase.0.3/textureOption.html

**Comment by sjshin-simpson** [comment]
73156bd 확인필요!!
