### ISSUE TITLE
[Document] Camera

### ISSUE THREAD

**Issue by shallaa** [projectBS/MoGL#349]
- projectionMatrix
    sample 없음

- resetProjectionMatrix
    sample 없음

- resize
    sample 없음

- othogonal
    sample 없음

- perspective
    sample 없음

**Comment by pparkssi** [comment]
resize 상수는 기능을 몰라서 처리 하지 못했습니다.

**Comment by shallaa** [comment]
resize는 지금은 사용되지 않는 것으로 보이는데.. 제거해도 무방할 것 같습니다.
@projectBS/mogl 혹시 resize 의 용도나 히스토리를 아시는 분 있으신가요?

**Comment by redcamel** [comment]
네 0.2의 찌끄러기군요..삭제하것습니다.
