### ISSUE TITLE
[Document] Matrix

### ISSUE THREAD

**Issue by shallaa** [projectBS/MoGL#350]
- matLookAt
    description 없음
    sample 없음

- _frustum
    private 인지 확인

**Comment by shallaa** [comment]
@redcamel 헬프!!! frustum 메서드의 파라미터를 파악 못했음. ㅠ

**Comment by redcamel** [comment]
frumstum은 절두체 생성인데...
음 이게..굳이 외부로 빠질필요가 없어보임...내부처리로 변경하것음
