### ISSUE TITLE
[Document] Scene

### ISSUE THREAD

**Issue by shallaa** [projectBS/MoGL#352]
- addFragmentShader
    sample 없음

- addVertexShader
    sample 없음

**Comment by fabulousu** [comment]
this - 메소드체이닝을 위해 자신을 반환함 - 메서드체이닝을 위해 자신을 반환함. 

같은 말이 2번 반복 됨

**Comment by hanmomhanda** [comment]
addVertexShader와 addFragmentShader만 method 함수의 두번쨰 파라미터에 설정 객체가 아니라 함수 정의가 바로 나오고 있음. 

두 메서드는 sample 뿐 아니라 description, param 등 모든 문서화가 안되어 있는 걸로 추정됩니다.

**Comment by fabulousu** [comment]
#352 addFragmentShader, addVertexShader 문서화 완료
