### ISSUE TITLE
0706 - 모델로딩시 모델파일을 txt나 html로 수정

### ISSUE THREAD

**Issue by redcamel** [projectBS/MoGL#361]
웹서버 마임타입설정에 걸리는경우가 빈번함

**Comment by shallaa** [comment]
*.babylon 파일들은 *.json으로 수정하겠음.

**Comment by redcamel** [comment]
넵

**Comment by shallaa** [comment]
https://github.com/projectBS/MoGL/commit/05e00be70a5392b35db95e86b1500c3cf0e0fa4a
