### ISSUE TITLE
Geometry 구현

### ISSUE THREAD

**Issue by hikaMaeng** [projectBS/MoGL#5]
Geometry 구현

**Comment by redcamel** [comment]
진행중

**Comment by hikaMaeng** [comment]
https://github.com/projectBS/MoGL/commit/2414d7411ea7690f4d6ffa0de52cf1d6d5ef47eb

생성자 구현문제
일단 info를 완전히 무시한다는 점과 배열의 구조를 함부로 추측한다는거.
info에 ['x', 'y', 'z', 'u', 'v', 'nx', 'ny', nz']  라고 보내면 정점을 해석하는 방법이 전혀 달라지는데..
암묵적으로 코드가 [x,y,z, x,y,z, x,y,z...] 로 들어온다고 가정하고 있는데..
이건 info생략시 기본값이 ['x', 'y', 'z'] 이기 때문일뿐..
그리고 내부에서는 typedArray로 저장하게 되어있는데 그것도 처리안되어있음.
일단 인자로 넘어온거 자체가 원하는 TypedArray인지 확인해보고 아니면 TypeArray로 우리가 원하는 형식으로 변환해서 집어넣어야함.

**Comment by hikaMaeng** [comment]
정적요소에 대한 선언이 잘못되었음.
1. fn이 아닌 클래스에 정의되어야함.
...
Geometry = MoGL.ext( Geometry, MoGL );
Geometry.x = 'x';
...
return Geometry;

이런 형태로 작성되어야함.
2. 문서화 다른 이름으로 작성되었음. 대문자, 언더스코어 등.

**Comment by redcamel** [comment]
정적요소에 대한 선언은 처리완료
생성자 구현문제는 - 현재 고민진행중
