### ISSUE TITLE
Mesh 구현

### ISSUE THREAD

**Issue by hikaMaeng** [projectBS/MoGL#7]
Mesh 구현

**Comment by redcamel** [comment]
진행중

**Comment by hikaMaeng** [comment]
1. _와 __의 사용.
언제 _인지 __인지 구별이 안됨. 문서에 노출되지 않는 속성은 전부 _로 통일
_geometry
_material
_scene
_parent

2. children
Group만 children을 갖고 Mesh는 갖지 않음.

3. matrix
get에서 현재 상태를 제대로 반영하지 않음.
평소에는 x, y, x 등의 속성을 변경하고 get시점에 matrix를 변경하여 반환함.

**Comment by hikaMaeng** [comment]
setMaterial, getMaterial
setGeometry, getGeometry 등에 구현문제 및 예외 미구현
