### ISSUE TITLE
World - removeRender param error

### ISSUE THREAD

**Issue by sjshin-simpson** [projectBS/MoGL#82]
문서상 나와 있는 error 가 모두 안되고 있음.

World test fail난 상태롤 커밋한 상태입니다. 참고바랍니다.

**Comment by redcamel** [comment]
월드의 렌더 리스트에 등록되지않은..
scene과 camera도 에러 검출하게 업데이트 하였습니다.

**Comment by redcamel** [comment]
테케 검수부탁드립니당~
