### ISSUE TITLE
World - addRender 호출 전 child Camera destroy

### ISSUE THREAD

**Issue by sjshin-simpson** [projectBS/MoGL#83]
addRender 호출 전에 child Camera destroy를 해도 

아무 이상없이 addRender가 진행됩니다.

addRender이후 과정에서 camera내부 메서드 호출시 error를 기다리는 것이 나을지
addRender 호출 시 destroy가 되어있는 객체를 찾을지

의견바랍니다.

해당 내용 World test에 커밋한 상태입니다. 참고바랍니다.

**Comment by redcamel** [comment]
렌더 추가시 카메라와 씬이 살아있는지 체크하고 등록되도록 변경완료
살아있지 않다면 World.addRender:0,World.addRender:1 로 에러 발생
