### ISSUE TITLE
Mesh - x-coordinate reversed

### ISSUE THREAD

**Issue by pparkssi** [projectBS/MoGL#84]
Mesh.x가 반대로 동작중입니다.

랜더함수에서 프레임버퍼사용으로 인해서 발생하는 문제로 보입니다.
(좌우 반전)

**Comment by redcamel** [comment]
음 이건좀 오묘한 문제인데....
카메라 룩엣구현에 구현을 해보고 결정을 함시 좋을듯합니다.

**Comment by hikaMaeng** [comment]
오묘하기 이전에 이슈에 마일스톤이 반영되어있지 않음. 항상 이슈 쓸때 오른쪽에 마일스톤과 레이블을 달도록 합시다.

**Comment by redcamel** [comment]
카메라를 본격적으로 가지고놀기전에 일단 원하시는대로 반영

**Comment by pparkssi** [comment]
카메라 시점 문제였나 보군요
