### ISSUE TITLE
Scene - addChild error handling 1

### ISSUE THREAD

**Issue by sjshin-simpson** [projectBS/MoGL#90]
Scene 문서상

'Scene.addChild:3' - Mesh안의 Material에 지정된 fragment shader의 id가 존재하지 않음.

이라 되어있는데요. material 안에 fragment shader 를 추추가하는 부분이 없어서요.

제가 잘못 이해한건지 문서가 잘못된건지 잘몰라서 올립니다.

추가로 수정하시면 테스트작성해서 올리겠습니다.

**Comment by redcamel** [comment]
재질의 fragment shader는 아직 미구현된것이 맞습니다....
아마도 커스텀 쉐이더쪽은 확확 뒤로 밀릴지도....

커스텀전에..
setEdge
setLambert
setShading
setWireFrame
가 먼저 반영될 예정입니다~
