### ISSUE TITLE
Scene - addChild error handling 2

### ISSUE THREAD

**Issue by sjshin-simpson** [projectBS/MoGL#91]
테스트 작성중 문서상 아래와 같이 되어있는데요.

'Scene.addChild:2' - Mesh안의 Geometry에 지정된 vertex shader의 id가 존재하지 않음.

해당 에러를 뿜을라면 아래와 같이 addVertexShader를 무조건 해야 에러가 나옵니다.
addVertexShader를 안하고 addChild하는 것도 id가 존재하지 않는 거라 생각이 들어서 해봤는데 그냥 넘어 가더라구요 이부분은 어떻게 되는지 알고싶습니다.
![2015-05-18 1 12 45](https://cloud.githubusercontent.com/assets/11942622/7671142/24a1ed0e-fcfb-11e4-804d-d9b8220276f0.png)

테스트는 아직 푸시안한 상태입니다.

**Comment by redcamel** [comment]
네없으면 기본 쉐이더라고 가정하는 방향입니다...
지오메트리를 구부린다던지....웨이브친다던지...이런건...
기본쉐이더 + 추가된 쉐이더 형태로 차차 진행예정입니다.
