### ISSUE TITLE
테스트를 해보려고 helloWord를 시도하는데요.

### ISSUE THREAD

**Issue by tom-axisj** [projectBS/MoGL#94]
![2015-05-18 11 26 09](https://cloud.githubusercontent.com/assets/5884902/7673560/bb75013a-fd50-11e4-86d9-12cc4d6a6e0f.png)

경고가 무지 많이 뜨고 기대했던 도형은 보이지 않는데요.
제 환경이 문제 인가요? 아님 아직 hellowWorld가 준비 안된건가요?

**Comment by shallaa** [comment]
배포버전( https://github.com/projectBS/MoGL/tree/master/lib ) 을 사용하신 건가요?
dev 브랜치는 업뎃이 계속 발생해서 말씀하신 현상이 발생할 수도 있어요.
